// src/app/types/color.types.ts

export interface Color {
  id: string;
  name: string;        // "Negro", "Cognac", "Miel"
  slug: string;        // "negro", "cognac", "miel" (auto-generated by BE)
  hex: string;         // "#1a1a1a"
  createdAt: string;
  updatedAt: string;
}

export interface ColorFormData {
  name: string;
  hex: string;
  slug?: string;
}

// BE raw shape — MongoDB usa _id
export interface ColorBe {
  _id: string;         // ← MongoDB siempre devuelve _id
  id?: string;         // por si el serializer del BE lo mapea a id
  tenantId: string;
  name: string;
  slug: string;
  hex: string;
  createdAt: string;
  updatedAt: string;
}