// src/app/types/color.ts

export interface Color {
  id: string;
  name: string;        // "Negro", "Cognac", "Miel"
  slug: string;        // "negro", "cognac", "miel" (auto-generated by BE)
  hex: string;         // "#1a1a1a"
  createdAt: string;
  updatedAt: string;
}

export interface ColorFormData {
  name: string;
  hex: string;
}

// BE raw shape (MongoDB _id → id)
export interface ColorBe {
  id: string;
  tenantId: string;
  name: string;
  slug: string;
  hex: string;
  createdAt: string;
  updatedAt: string;
}
